import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Layout from '../comps/Layout'
import LawDetails from '../comps/LawDetails'
import React from 'react';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Draft Law Registration</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
      <LawDetails />
      </Layout>
    </div>
  )
}